apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-rkqe
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-rkqe@sha256:dfa143ca901cff211aa35cefbf31bfeeb8ce762927daae598c45242bea79861b
        name: my-nodejs
        resources: {}
status: {}
